DROP TRIGGER IF EXISTS forum_inc_thread_count ON thread;
DROP FUNCTION IF EXISTS forum_inc_thread_count();

DROP TABLE IF EXISTS vote;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS thread;
DROP TABLE IF EXISTS forum_fuser;
DROP TABLE IF EXISTS forum;
DROP TABLE IF EXISTS fuser;

DROP EXTENSION IF EXISTS citext CASCADE;
