DROP TABLE IF EXISTS vote CASCADE;
DROP TABLE IF EXISTS post CASCADE;
DROP TABLE IF EXISTS thread CASCADE;
DROP TABLE IF EXISTS forum_user CASCADE;
DROP TABLE IF EXISTS forum CASCADE;
DROP TABLE IF EXISTS fuser CASCADE;

DROP EXTENSION IF EXISTS citext CASCADE;
