CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE IF NOT EXISTS fuser (
  nickname CITEXT PRIMARY KEY,
  fullname TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  about TEXT
);

CREATE TABLE IF NOT EXISTS forum (
  slug TEXT PRIMARY KEY,
  author CITEXT REFERENCES fuser(nickname) NOT NULL,
  title TEXT NOT NULL,
  posts INTEGER DEFAULT 0,
  threads INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS thread (
  id SERIAL PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  forum TEXT REFERENCES forum(slug) NOT NULL,
  author CITEXT REFERENCES fuser(nickname) NOT NULL,
  created TIMESTAMP WITH TIME ZONE DEFAULT now(),
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  votes INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS vote (
  id INTEGER REFERENCES thread(id) NOT NULL,
  fuser CITEXT REFERENCES fuser(nickname) NOT NULL,
  value INTEGER NOT NULL,
  PRIMARY KEY(id, fuser)
);

CREATE TABLE IF NOT EXISTS forum_fuser (
  forum TEXT REFERENCES forum(slug) NOT NULL,
  fuser CITEXT REFERENCES fuser(nickname) NOT NULL,
  PRIMARY KEY(forum, fuser)
);

CREATE TABLE IF NOT EXISTS post (
  id SERIAL PRIMARY KEY,
  author CITEXT REFERENCES fuser(nickname) NOT NULL,
  thread INTEGER REFERENCES thread(id) NOT NULL,
  forum TEXT NOT NULL,
  message TEXT NOT NULL,
  parent INTEGER DEFAULT 0,
  is_edited BOOLEAN DEFAULT false,
  created TIMESTAMP WITH TIME ZONE DEFAULT now()
);
