// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonEcf4a92eDecodeForumDBModels(in *jlexer.Lexer, out *ErrorPostIncorrectThreadOfParent) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "CurThreadId":
			out.CurThreadId = int(in.Int())
		case "ParentThreadId":
			out.ParentThreadId = int(in.Int())
		case "message":
			out.Message = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEcf4a92eEncodeForumDBModels(out *jwriter.Writer, in ErrorPostIncorrectThreadOfParent) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"CurThreadId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.CurThreadId))
	}
	{
		const prefix string = ",\"ParentThreadId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.ParentThreadId))
	}
	{
		const prefix string = ",\"message\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Message))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ErrorPostIncorrectThreadOfParent) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEcf4a92eEncodeForumDBModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ErrorPostIncorrectThreadOfParent) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEcf4a92eEncodeForumDBModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ErrorPostIncorrectThreadOfParent) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEcf4a92eDecodeForumDBModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ErrorPostIncorrectThreadOfParent) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEcf4a92eDecodeForumDBModels(l, v)
}
